version: '2.1'
services:
  registry:
    #build: ./registry
    image: lecarden_registry:latest
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
    healthcheck:
      test: "true"
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - app-network
  gateway:
    #build: ./gateway
    image: lecarden_gateway:latest
    depends_on:
      registry:
        condition: service_healthy
    ports:
      - 4000:4000
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
    healthcheck:
      test: "true"
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  auth-service:
    #build: ./auth-service
    image: lecarden_auth-service:latest
    depends_on:
      registry:
        condition: service_healthy
      gateway:
        condition: service_healthy
    ports:
      - 5000:5000
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - DB_USERNAME=${AUTH_SERVICE_DB_USERNAME}
      - DB_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
    healthcheck:
      test: "true"
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - app-network


  word-service:
    #build: ./word-service
    image: lecarden_word-service:latest
    depends_on:
      registry:
        condition: service_healthy
      gateway:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    ports:
      - 6002:6002
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - DB_USERNAME=${WORD_SERVICE_DB_USERNAME}
      - DB_PASSWORD=${WORD_SERVICE_DB_PASSWORD}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - app-network

  result-service:
    #build: ./result-service
    image: lecarden_result-service:latest
    depends_on:
      registry:
        condition: service_healthy
      gateway:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    ports:
      - 6006:6006
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - DB_USERNAME=${RESULT_SERVICE_DB_USERNAME}
      - DB_PASSWORD=${RESULT_SERVICE_DB_PASSWORD}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - app-network

  basket-service:
    #build: ./basket-service
    image: lecarden_basket-service:latest
    depends_on:
      registry:
        condition: service_healthy
      gateway:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    ports:
      - 6004:6004
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - DB_USERNAME=${BASKET_SERVICE_DB_USERNAME}
      - DB_PASSWORD=${BASKET_SERVICE_DB_PASSWORD}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - app-network

  user-service:
    #build: ./user-service
    image: lecarden_user-service:latest
    depends_on:
      registry:
        condition: service_healthy
      gateway:
        condition: service_healthy
    ports:
      - 6000:6000
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - DB_USERNAME=${USER_SERVICE_DB_USERNAME}
      - DB_PASSWORD=${USER_SERVICE_DB_PASSWORD}
    networks:
      - app-network

  email-service:
    #build: ./email-service
    image: lecarden_email-service:latest
    depends_on:
      registry:
        condition: service_healthy
      gateway:
        condition: service_healthy
    ports:
      - 9093:9093
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - EMAIL_LOGIN=${EMAIL_LOGIN}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "kafkatopic:1:3"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
