spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared-dev
  profiles:
    active: dev
  security:
    user:
      password: password

server:
  port: 8888

