server:
  servlet:
    context-path: /uaa
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lecarden?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect