server:
  servlet:
    context-path: /baskets
  port: 6004

spring:
  zipkin:
    sender:
      type: web
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/lecarden_basket?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: basket-service
      clientSecret: password
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server