server:
  servlet:
    context-path: /users
  port: 6000

spring:
  zipkin:
    sender:
      type: web
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/lecarden?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
feign:
  hystrix:
    enabled: true

email:
  register-confirmation:
    url: http://email-service/register-confirmation
  forgot-password:
    url: http://email-service/forgot-password-token