server:
  servlet:
    context-path: /uaa
  port: 5000
spring:
  datasource:
    URL: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect