server:
  servlet:
    context-path: /uaa
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/lecarden?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect