server:
  servlet:
    context-path: /baskets
  port: 6004

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${BASKET_DB_URL}
    username: ${BASKET_DB_USERNAME}
    password: ${BASKET_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: basket-service
      clientSecret: ${BASKET_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server