hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: http://localhost:5000
      stripPrefix: false
      sensitiveHeaders:

    word-service:
      path: /words/**
      serviceId: word-service
      stripPrefix: false
      sensitiveHeaders:

    basket-service:
      path: /baskets/**
      serviceId: basket-service
      stripPrefix: false
      sensitiveHeaders:

    result-service:
      path: /results/**
      serviceId: result-service
      stripPrefix: false
      sensitiveHeaders:

    user-service:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
      sensitiveHeaders:
server:
  port: 4000
