server:
  servlet:
    context-path: /results
  port: 6006

spring:
  zipkin:
    sender:
      type: web
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/lecarden_result?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: result-service
      clientSecret: password
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server