server:
  servlet:
    context-path: /results
  port: 6006

spring:
  zipkin:
    sender:
      type: web
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${RESULT_DB_URL}
    username: ${RESULT_DB_USERNAME}
    password: ${RESULT_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: result-service
      clientSecret: ${RESULT_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server