server:
  servlet:
    context-path: /users
  port: 6000

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

feign:
  hystrix:
    enabled: true

email:
  register-confirmation:
    url: ${EMAIL_REGISTER_CONFIRMATION_URL}
  forgot-password:
    url: ${EMAIL_FORGOT_PASSWORD_URL}