server:
  servlet:
    context-path: /words
  port: 6002

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${WORD_DB_URL}
    username: ${WORD_DB_USERNAME}
    password: ${WORD_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      clientId: word-service
      clientSecret: ${WORD_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

result:
  results:
    url: ${RESULT_RESULTS_URL}